version: "3.9"
services:
  jokehub_backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - ROCKER_ADDRESS=0.0.0.0
    container_name: jokehub_backend
    restart: unless-stopped