[package]
name = "jokehub"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
diesel_migrations = "1.4.0"
chrono = { version = "0.4", features = ["serde"] }
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.15", features = ["derive"] }
warp = "0.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.diesel]
version = "1.4.7"
features = ["postgres", "uuidv07", "chrono"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["diesel_postgres_pool"]
