[package]
name = "jokehub"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json", "msgpack", "uuid"]

[dependencies.uuid]
version = "1.0.0"
features = [ "v4", "fast-rng", "macro-diagnostics"]

[dependencies.diesel]
version = "1.4.4"
features = ["postgres"]
