version: "3.9"
services:
  jokehub_ngnix:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
    container_name: jokehub_ngnix
    restart: unless-stopped

  jokehub_backend:
    build:
      dockerfile: ci/docker/backend.Dockerfile
      context: ../../
    environment:
      - MONGO_DB_URL=mongodb://$MONGO_USER:$MONGO_USER_PASSWORD@jokehub_mongodb:27017/$MONGO_INITDB_DATABASE?w=majority
      - MONGO_DATABASE_NAME=$MONGO_INITDB_DATABASE
    depends_on:
      jokehub_mongodb:
        condition: service_healthy
    container_name: jokehub_backend
    restart: unless-stopped

  jokehub_mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ../tools/mongodb_init.sh:/docker-entrypoint-initdb.d/mongodb_init.sh
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "'db.runCommand({serverStatus:1}).ok'",
          "|",
          "mongo admin",
          "-u $MONGO_INITDB_ROOT_USERNAME",
          "-p $MONGO_INITDB_ROOT_PASSWORD",
          "--quiet | grep 1",
        ]
      interval: 1s
      timeout: 10s
      retries: 3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_USER=$MONGO_USER
      - MONGO_USER_PASSWORD=$MONGO_USER_PASSWORD
      - MONGO_USER_ROLE=$MONGO_USER_ROLE
      - MONGO_JOKERHUB_SITH_HASH=$MONGO_JOKERHUB_SITH_HASH
    container_name: jokehub_mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  default:
    name: jokehub_net
