version: "3.9"
services:
  jokehub_mongodb_test:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_test:/data/db
      - ../tools/mongodb_test_init.sh:/docker-entrypoint-initdb.d/mongodb_test_init.sh
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "'db.runCommand({serverStatus:1}).ok'",
          "|",
          "mongo admin",
          "-u $MONGO_INITDB_ROOT_USERNAME",
          "-p $MONGO_INITDB_ROOT_PASSWORD",
          "--quiet | grep 1",
        ]
      interval: 1s
      timeout: 10s
      retries: 3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_USER=$MONGO_USER
      - MONGO_USER_PASSWORD=$MONGO_USER_PASSWORD
      - MONGO_USER_ROLE=$MONGO_USER_ROLE
    container_name: jokehub_mongodb_test
    restart: unless-stopped

  jokehub_redis_test:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:35006:6379"
    healthcheck:
      test: [
        "CMD", 
        "redis-cli", 
        "--raw", 
        "incr", 
        "ping"
      ]
      interval: 1s
      timeout: 10s
      retries: 3
    volumes:
      - redis_data_test:/var/lib/redis
    container_name: jokehub_redis_test
    restart: unless-stopped

volumes:
  mongodb_data_test:
    driver: local

  redis_data_test:
    driver: local

networks:
  default:
    name: jokehub_net
