#!/bin/bash

source .env.test

function backend {
cat << EOF > backend/.env
SERVER_PORT=$TEST_SERVER_PORT
SERVER_HOST=$TEST_SERVER_HOST

MONGO_DB_URL=$TEST_MONGO_DB_URL
MONGO_DATABASE_NAME=$TEST_MONGO_INITDB_DATABASE

REDIS_DB_URL=redis://$TEST_REDIS_ADDRESS:$TEST_REDIS_PORT/$TEST_REDIS_DB
EOF
}

backend